// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy0dHUo2UMmbR0YEJeajNGKx7k8Y9cq-4',
    appId: '1:164791195335:web:04782fb71a1f25b6ab90e2',
    messagingSenderId: '164791195335',
    projectId: 'smart-doc-1d42f',
    authDomain: 'smart-doc-1d42f.firebaseapp.com',
    storageBucket: 'smart-doc-1d42f.firebasestorage.app',
    measurementId: 'G-7T1NJ81ZY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAabtca6uj49of1hihmT0CAOd1InEQD4e0',
    appId: '1:164791195335:android:13e4888588bafda4ab90e2',
    messagingSenderId: '164791195335',
    projectId: 'smart-doc-1d42f',
    storageBucket: 'smart-doc-1d42f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtSVsanQskZx3KlemNwj3fDptGAFCUaxI',
    appId: '1:164791195335:ios:3e0f574d2fb5163cab90e2',
    messagingSenderId: '164791195335',
    projectId: 'smart-doc-1d42f',
    storageBucket: 'smart-doc-1d42f.firebasestorage.app',
    iosBundleId: 'com.example.smartDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy0dHUo2UMmbR0YEJeajNGKx7k8Y9cq-4',
    appId: '1:164791195335:web:0e7e2e36cc79996eab90e2',
    messagingSenderId: '164791195335',
    projectId: 'smart-doc-1d42f',
    authDomain: 'smart-doc-1d42f.firebaseapp.com',
    storageBucket: 'smart-doc-1d42f.firebasestorage.app',
    measurementId: 'G-GZ2E20ZQBD',
  );
}
